In [1]:
from Farm_Evaluator_Vec import find_aep
import pandas as pd
import numpy as np

In [2]:
import os 
from glob import glob

In [24]:
WIND_DATA_270 = 'wind_data/wind_270.csv'
WIND_DATA_225 = 'wind_data/wind_225.csv'
WIND_DATA_224 = 'wind_data/wind_224.csv'
WIND_DATA_180 = 'wind_data/wind_180.csv'
WIND_DATA_FULL = 'wind_data/full_wind_data.csv'

POWER_CURVE = 'power_curve.csv'

In [4]:
files = glob('turbine_data/*csv')

# wind data = 270

In [5]:
wind_data = pd.read_csv(WIND_DATA_270)
wind_data.head()

               date  drct       sped
0  2007-01-01 00:20   270  12.829798
1  2007-01-01 00:50   270  15.842659
2  2007-01-01 01:20   270  15.270610
3  2007-01-01 01:50   270  13.332094
4  2007-01-01 02:20   270  12.639211

In [6]:
wind_data.describe()

          drct          sped
count  15548.0  15548.000000
mean     270.0      8.961912
std        0.0      4.612641
min      270.0      0.680265
25%      270.0      5.415578
50%      270.0      8.532853
75%      270.0     11.820551
max      270.0     29.879753

In [12]:
aep_270 = {}
for file in files:
    name = file.split('/')[-1]
    aep = find_aep(file,POWER_CURVE,WIND_DATA_270)
    aep_270[name] = aep
    print(aep)

Both perimeter and proximity constraints are satisfied !!

468.1563427734375
Both perimeter and proximity constraints are satisfied !!

479.078874206543
Both perimeter and proximity constraints are satisfied !!

482.45012283325195
Both perimeter and proximity constraints are satisfied !!

442.5678689575195
Both perimeter and proximity constraints are satisfied !!

475.81709884643556
Both perimeter and proximity constraints are satisfied !!

439.39301055908203
Both perimeter and proximity constraints are satisfied !!

479.16676025390626
Both perimeter and proximity constraints are satisfied !!

485.9349884033203
Both perimeter and proximity constraints are satisfied !!

479.41848861694336
Both perimeter and proximity constraints are satisfied !!

476.3501293945312
Both perimeter and proximity constraints are satisfied !!

467.04079147338865
Both perimeter and proximity constraints are satisfied !!

471.97200073242186
Both perimeter and proximity constraints are satisfied !!

439.30458984375
Both perimeter and proximity constraints are satisfied !!

479.6174519348144
Both perimeter and proximity constraints are satisfied !!

467.02321426391603
Both perimeter and proximity constraints are satisfied !!

471.97203414916993
Both perimeter and proximity constraints are satisfied !!

477.7320790100098
Both perimeter and proximity constraints are satisfied !!

481.3279884338379
Both perimeter and proximity constraints are satisfied !!

484.0155972290039
Both perimeter and proximity constraints are satisfied !!

503.75059295654296
Both perimeter and proximity constraints are satisfied !!

471.44374877929687
Both perimeter and proximity constraints are satisfied !!

478.6391098022461
Both perimeter and proximity constraints are satisfied !!

471.30192810058594
Both perimeter and proximity constraints are satisfied !!

467.02321426391603
Both perimeter and proximity constraints are satisfied !!

479.37955810546873
Both perimeter and proximity constraints are satisfied !!

471.5425955200195
Both perimeter and proximity constraints are satisfied !!

477.55797775268553
Both perimeter and proximity constraints are satisfied !!

470.7903511047363
Both perimeter and proximity constraints are satisfied !!

471.44374877929687
Both perimeter and proximity constraints are satisfied !!

477.69197891235353
Both perimeter and proximity constraints are satisfied !!

381.1004342651367
Both perimeter and proximity constraints are satisfied !!

485.9349884033203
Both perimeter and proximity constraints are satisfied !!

452.85959243774414
Both perimeter and proximity constraints are satisfied !!

485.96626647949216
Both perimeter and proximity constraints are satisfied !!

444.7401580810547
Both perimeter and proximity constraints are satisfied !!

471.61163452148435
Both perimeter and proximity constraints are satisfied !!

478.4499710083008
Both perimeter and proximity constraints are satisfied !!

448.7178204345703
Both perimeter and proximity constraints are satisfied !!

471.5425955200195
Both perimeter and proximity constraints are satisfied !!

471.5425955200195
Both perimeter and proximity constraints are satisfied !!

486.87339752197266
Both perimeter and proximity constraints are satisfied !!

448.2133277893066
Both perimeter and proximity constraints are satisfied !!

444.7401580810547
Both perimeter and proximity constraints are satisfied !!

465.43932723999023

In [13]:
df = pd.DataFrame(aep_270,index = [1]).T
df.to_csv('scores/scores_wind_270')

In [14]:
df.sort_values(by = 1,ascending = False)

                               1
turbine_loc_test.csv  503.750593
manual2.csv           486.873398
kmeans.csv            485.966266
rotated30.csv         485.934988
rotated60.csv         485.934988
rotated_best70.csv    484.015597
rotated_best20.csv    482.450123
pattern4.csv          481.327988
rotated_best40.csv    479.617452
rotated_best60.csv    479.418489
rotated_best10.csv    479.379558
rotated_best30.csv    479.166760
rotated100.csv        479.078874
pattern2.csv          478.639110
pattern8.csv          478.449971
rotated_best100.csv   477.732079
pattern9.csv          477.691979
rotated_best50.csv    477.557978
rotated_best80.csv    476.350129
pattern6.csv          475.817099
rotated50.csv         471.972034
rotated40.csv         471.972001
wake1.csv             471.611635
wake3.csv             471.542596
rotated0.csv          471.542596
rotated90.csv         471.542596
rotated10.csv         471.443749
rotated80.csv         471.443749
pattern7.csv          471.301928
wake2.csv             470.790351
rotated_best90.csv    468.156343
pattern3.csv          467.040791
rotated70.csv         467.023214
rotated20.csv         467.023214
pattern1.csv          465.439327
pattern10.csv         452.859592
pattern11.csv         448.717820
pattern12a.csv        448.213328
rotated_best0.csv     444.740158
pattern12.csv         444.740158
pattern13a.csv        442.567869
pattern13.csv         439.393011
pattern5.csv          439.304590
manual1.csv           381.100434

# Wind 225

In [15]:
data = pd.read_csv(WIND_DATA_225)
print(data.shape)
data.head()

(15548, 3)

               date  drct       sped
0  2007-01-01 00:20   225  12.829798
1  2007-01-01 00:50   225  15.842659
2  2007-01-01 01:20   225  15.270610
3  2007-01-01 01:50   225  13.332094
4  2007-01-01 02:20   225  12.639211

In [16]:
data.describe()

          drct          sped
count  15548.0  15548.000000
mean     225.0      8.961912
std        0.0      4.612641
min      225.0      0.680265
25%      225.0      5.415578
50%      225.0      8.532853
75%      225.0     11.820551
max      225.0     29.879753

In [18]:
aep_225 = {}
for file in files:
    name = file.split('/')[-1]
    aep = find_aep(file,POWER_CURVE,WIND_DATA_225,debug = False)
    aep_225[name] = aep
    print(aep)

Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan
Both perimeter and proximity constraints are satisfied !!

nan

# Wind 224

In [88]:
data = pd.read_csv(WIND_DATA_224)
print(data.shape)
data.head()

(15548, 3)

               date  drct       sped
0  2007-01-01 00:20   224  12.829798
1  2007-01-01 00:50   224  15.842659
2  2007-01-01 01:20   224  15.270610
3  2007-01-01 01:50   224  13.332094
4  2007-01-01 02:20   224  12.639211

In [89]:
data.describe()

          drct          sped
count  15548.0  15548.000000
mean     224.0      8.961912
std        0.0      4.612641
min      224.0      0.680265
25%      224.0      5.415578
50%      224.0      8.532853
75%      224.0     11.820551
max      224.0     29.879753

In [90]:
aep_224 = {}
for file in files:
    name = file.split('/')[-1]
    aep = find_aep(file,POWER_CURVE,WIND_DATA_224)
    aep_224[name] = aep
    print(aep)
    break

Both perimeter and proximity constraints are satisfied !!

nan

# Wind data = 180

In [20]:
data = pd.read_csv(WIND_DATA_180)
print(data.shape)
data.head()

(15548, 3)

               date  drct       sped
0  2007-01-01 00:20   180  12.829798
1  2007-01-01 00:50   180  15.842659
2  2007-01-01 01:20   180  15.270610
3  2007-01-01 01:50   180  13.332094
4  2007-01-01 02:20   180  12.639211

In [21]:
data.describe()

          drct          sped
count  15548.0  15548.000000
mean     180.0      8.961912
std        0.0      4.612641
min      180.0      0.680265
25%      180.0      5.415578
50%      180.0      8.532853
75%      180.0     11.820551
max      180.0     29.879753

In [22]:
aep_180 = {}
for file in files:
    name = file.split('/')[-1]
    aep = find_aep(file,POWER_CURVE,WIND_DATA_180)
    aep_180[name] = aep
    print(aep)

Both perimeter and proximity constraints are satisfied !!

444.55409362792966
Both perimeter and proximity constraints are satisfied !!

471.44374877929687
Both perimeter and proximity constraints are satisfied !!

481.06062103271483
Both perimeter and proximity constraints are satisfied !!

462.4847186279297
Both perimeter and proximity constraints are satisfied !!

469.85718841552733
Both perimeter and proximity constraints are satisfied !!

457.8908514404297
Both perimeter and proximity constraints are satisfied !!

477.831360168457
Both perimeter and proximity constraints are satisfied !!

482.00370849609374
Both perimeter and proximity constraints are satisfied !!

479.0109713745117
Both perimeter and proximity constraints are satisfied !!

480.48896072387697
Both perimeter and proximity constraints are satisfied !!

410.44301239013674
Both perimeter and proximity constraints are satisfied !!

449.577332611084
Both perimeter and proximity constraints are satisfied !!

439.30458984375
Both perimeter and proximity constraints are satisfied !!

478.73989471435544
Both perimeter and proximity constraints are satisfied !!

472.79445373535157
Both perimeter and proximity constraints are satisfied !!

449.577332611084
Both perimeter and proximity constraints are satisfied !!

479.58827911376954
Both perimeter and proximity constraints are satisfied !!

418.7036993408203
Both perimeter and proximity constraints are satisfied !!

479.4955810546875
Both perimeter and proximity constraints are satisfied !!

508.5024545288086
Both perimeter and proximity constraints are satisfied !!

479.078874206543
Both perimeter and proximity constraints are satisfied !!

410.44301239013674
Both perimeter and proximity constraints are satisfied !!

464.79425033569333
Both perimeter and proximity constraints are satisfied !!

472.79445373535157
Both perimeter and proximity constraints are satisfied !!

477.7321124267578
Both perimeter and proximity constraints are satisfied !!

471.5425955200195
Both perimeter and proximity constraints are satisfied !!

481.1485070800781
Both perimeter and proximity constraints are satisfied !!

470.7903845214844
Both perimeter and proximity constraints are satisfied !!

479.078874206543
Both perimeter and proximity constraints are satisfied !!

460.34237091064455
Both perimeter and proximity constraints are satisfied !!

486.8733641052246
Both perimeter and proximity constraints are satisfied !!

482.0036750793457
Both perimeter and proximity constraints are satisfied !!

454.2882252502441
Both perimeter and proximity constraints are satisfied !!

482.9424851989746
Both perimeter and proximity constraints are satisfied !!

468.15637619018554
Both perimeter and proximity constraints are satisfied !!

471.6117013549805
Both perimeter and proximity constraints are satisfied !!

464.79201141357424
Both perimeter and proximity constraints are satisfied !!

462.3008596801758
Both perimeter and proximity constraints are satisfied !!

471.5425955200195
Both perimeter and proximity constraints are satisfied !!

471.5425955200195
Both perimeter and proximity constraints are satisfied !!

381.10046768188477
Both perimeter and proximity constraints are satisfied !!

464.6682357788086
Both perimeter and proximity constraints are satisfied !!

468.15637619018554
Both perimeter and proximity constraints are satisfied !!

410.44301239013674

In [23]:
df = pd.DataFrame(aep_180,index = [1]).T
df.to_csv('scores/scores_wind_180')

df.sort_values(by = 1,ascending = False)

                               1
turbine_loc_test.csv  508.502455
manual1.csv           486.873364
kmeans.csv            482.942485
rotated60.csv         482.003708
rotated30.csv         482.003675
rotated_best50.csv    481.148507
rotated_best20.csv    481.060621
rotated_best80.csv    480.488961
rotated_best100.csv   479.588279
rotated_best70.csv    479.495581
rotated80.csv         479.078874
rotated10.csv         479.078874
rotated_best60.csv    479.010971
rotated_best40.csv    478.739895
rotated_best30.csv    477.831360
rotated_best10.csv    477.732112
rotated20.csv         472.794454
rotated70.csv         472.794454
wake1.csv             471.611701
rotated90.csv         471.542596
wake3.csv             471.542596
rotated0.csv          471.542596
rotated100.csv        471.443749
wake2.csv             470.790385
pattern6.csv          469.857188
rotated_best0.csv     468.156376
pattern12.csv         468.156376
pattern7.csv          464.794250
pattern8.csv          464.792011
pattern12a.csv        464.668236
pattern13a.csv        462.484719
pattern11.csv         462.300860
pattern9.csv          460.342371
pattern13.csv         457.890851
pattern10.csv         454.288225
rotated50.csv         449.577333
rotated40.csv         449.577333
rotated_best90.csv    444.554094
pattern5.csv          439.304590
pattern4.csv          418.703699
pattern2.csv          410.443012
pattern3.csv          410.443012
pattern1.csv          410.443012
manual2.csv           381.100468

# FULL Wind data

In [27]:
data = pd.read_csv(WIND_DATA_FULL,index_col = 0)
print(data.shape)
data.head()

(113113, 3)

               date   drct       sped
0  2007-01-01 00:20  290.0  12.829798
1  2007-01-01 00:50  290.0  15.842659
2  2007-01-01 01:20  290.0  15.270610
3  2007-01-01 01:50  300.0  13.332094
4  2007-01-01 02:20  290.0  12.639211

In [28]:
data.describe()

                drct           sped
count  113113.000000  113113.000000
mean      199.194345       8.882134
std        87.602702       4.682176
min        10.000000       0.069149
25%       140.000000       5.271903
50%       200.000000       8.240464
75%       260.000000      11.841516
max       360.000000      29.908987

In [29]:
aep_full = {}
for file in files:
    name = file.split('/')[-1]
    aep = find_aep(file,POWER_CURVE,WIND_DATA_FULL)
    aep_full[name] = aep
    print(aep)

Both perimeter and proximity constraints are satisfied !!

526.1309252929688
Both perimeter and proximity constraints are satisfied !!

523.5405926513672
Both perimeter and proximity constraints are satisfied !!

526.3437899780273
Both perimeter and proximity constraints are satisfied !!

524.9951234436035
Both perimeter and proximity constraints are satisfied !!

522.6006129455567
Both perimeter and proximity constraints are satisfied !!

521.9926286315917
Both perimeter and proximity constraints are satisfied !!

524.8107632446289
Both perimeter and proximity constraints are satisfied !!

522.8598934936523
Both perimeter and proximity constraints are satisfied !!

524.5650164794922
Both perimeter and proximity constraints are satisfied !!

526.6153344726563
Both perimeter and proximity constraints are satisfied !!

517.9808811950684
Both perimeter and proximity constraints are satisfied !!

523.9631140136719
Both perimeter and proximity constraints are satisfied !!

517.1153540039063
Both perimeter and proximity constraints are satisfied !!

525.6600833129883
Both perimeter and proximity constraints are satisfied !!

523.7189378356934
Both perimeter and proximity constraints are satisfied !!

523.4696823120117
Both perimeter and proximity constraints are satisfied !!

526.4201138305664
Both perimeter and proximity constraints are satisfied !!

522.0493702697754
Both perimeter and proximity constraints are satisfied !!

525.954351196289
Both perimeter and proximity constraints are satisfied !!

498.15395599365235
Both perimeter and proximity constraints are satisfied !!

524.1589361572265
Both perimeter and proximity constraints are satisfied !!

521.386081237793
Both perimeter and proximity constraints are satisfied !!

524.5343733215332
Both perimeter and proximity constraints are satisfied !!

523.2579537963867
Both perimeter and proximity constraints are satisfied !!

526.5626028442383
Both perimeter and proximity constraints are satisfied !!

524.398801574707
Both perimeter and proximity constraints are satisfied !!

525.607084350586
Both perimeter and proximity constraints are satisfied !!

523.514861755371
Both perimeter and proximity constraints are satisfied !!

523.9002905273437
Both perimeter and proximity constraints are satisfied !!

524.6586167907715
Both perimeter and proximity constraints are satisfied !!

523.4333583068848
Both perimeter and proximity constraints are satisfied !!

523.4725561523437
Both perimeter and proximity constraints are satisfied !!

524.3430958557129
Both perimeter and proximity constraints are satisfied !!

505.53885681152343
Both perimeter and proximity constraints are satisfied !!

526.1516770935059
Both perimeter and proximity constraints are satisfied !!

525.1260168457031
Both perimeter and proximity constraints are satisfied !!

524.4685423278809
Both perimeter and proximity constraints are satisfied !!

524.121442565918
Both perimeter and proximity constraints are satisfied !!

524.398801574707
Both perimeter and proximity constraints are satisfied !!

523.8647351074219
Both perimeter and proximity constraints are satisfied !!

524.7434619140626
Both perimeter and proximity constraints are satisfied !!

524.7320668029785
Both perimeter and proximity constraints are satisfied !!

526.1516770935059
Both perimeter and proximity constraints are satisfied !!

516.8897575378418

In [30]:
df = pd.DataFrame(aep_full,index = [1]).T
df.to_csv('scores/scores_wind_full.csv')

df.sort_values(by = 1,ascending = False)

                               1
rotated_best80.csv    526.615334
rotated_best10.csv    526.562603
rotated_best100.csv   526.420114
rotated_best20.csv    526.343790
pattern12.csv         526.151677
rotated_best0.csv     526.151677
rotated_best90.csv    526.130925
rotated_best70.csv    525.954351
rotated_best40.csv    525.660083
rotated_best50.csv    525.607084
wake1.csv             525.126017
pattern13a.csv        524.995123
rotated_best30.csv    524.810763
manual2.csv           524.743462
pattern12a.csv        524.732067
pattern9.csv          524.658617
rotated_best60.csv    524.565016
pattern7.csv          524.534373
pattern8.csv          524.468542
wake3.csv             524.398802
rotated0.csv          524.398802
pattern10.csv         524.343096
rotated10.csv         524.158936
pattern11.csv         524.121443
rotated40.csv         523.963114
rotated80.csv         523.900291
rotated90.csv         523.864735
rotated20.csv         523.718938
rotated100.csv        523.540593
wake2.csv             523.514862
rotated30.csv         523.472556
rotated50.csv         523.469682
manual1.csv           523.433358
rotated70.csv         523.257954
rotated60.csv         522.859893
pattern6.csv          522.600613
pattern4.csv          522.049370
pattern13.csv         521.992629
pattern2.csv          521.386081
pattern3.csv          517.980881
pattern5.csv          517.115354
pattern1.csv          516.889758
kmeans.csv            505.538857
turbine_loc_test.csv  498.153956